apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-app
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend-app
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.servicePort }}
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: frontend-app
      previewService: frontend-app-preview
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: frontend-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.servicePort }}
              protocol: TCP
