apiVersion: v1
kind: Secret
metadata:
  name: ecr-private-secret
  namespace: argocd
stringData:
  AWS_ACCESS_KEY_ID: "access_key"
  AWS_SECRET_ACCESS_KEY: "access_key_secret"
  AWS_ACCOUNT_ID: "account_id"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-private-cm
  namespace: argocd
data:
  AWS_REGION: "ap-southeast-1"
  DOCKER_SECRET_NAME: regcred
---

