apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend-app=913820192915.dkr.ecr.ap-southeast-1.amazonaws.com/backend-nashtech-hieptran-sd4871:*
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/backend-app.force-update: "true"
spec:
  project: backend
  source:
    repoURL: https://github.com/hieptran228/sd4871_msa
    targetRevision: HEAD
    path: ./deploy/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: app-argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
