apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: eks-frontend
    newName: 913820192915.dkr.ecr.ap-southeast-1.amazonaws.com/frontend-nashtech-hieptran-sd4871
    newTag: "5"
resources:
  - _deployment.yaml
  - _service.yaml
  - _ingress.yaml
